lagerregal/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include
from django.urls import path
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve
from favicon import conf
from rest_framework.urlpatterns import format_suffix_patterns

from lagerregal.api import views as api_views
from lagerregal.devicegroups import views as devicegroups_views
from lagerregal.devices import ajax as devices_ajax
from lagerregal.devices import views as devices_views
from lagerregal.devicetags import views as devicetags_views
from lagerregal.devicetypes import ajax as devicetypes_ajax
from lagerregal.devicetypes import views as devicetypes_views
from lagerregal.history import views as history_views
from lagerregal.locations import views as locations_views
from lagerregal.main import ajax as main_ajax
from lagerregal.main import views as main_views
from lagerregal.users import views as users_views

urlpatterns = [
    path("", login_required(main_views.Home.as_view()), name="home"),

    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("search/", devices_views.Search.as_view(), name="search"),

    path("devices/", devices_views.DeviceList.as_view(), name="device-list"),
    path("devices/add/", devices_views.DeviceCreate.as_view(), name="device-add"),
    path("devices/add/template/<int:templateid>/", devices_views.DeviceCreate.as_view(), name="device-add"),
    path("devices/add/copy/<int:copyid>/", devices_views.DeviceCreate.as_view(), name="device-add-copy"),
    path("devices/<int:pk>/", devices_views.DeviceDetail.as_view(), name="device-detail"),
    path("devices/<int:pk>/edit/", devices_views.DeviceUpdate.as_view(), name="device-edit"),
    path("devices/<int:pk>/delete/", devices_views.DeviceDelete.as_view(), name="device-delete"),
    path("devices/<int:pk>/archive/", devices_views.DeviceArchive.as_view(), name="device-archive"),
    path("devices/<int:pk>/trash/", devices_views.DeviceTrash.as_view(), name="device-trash"),
    path("devices/<int:pk>/storage/", devices_views.DeviceStorage.as_view(), name="device-storage"),
    path("devices/<int:pk>/mail/", devices_views.DeviceMail.as_view(), name="device-mail"),
    path("devices/<int:pk>/tags/", devicetags_views.DeviceTags.as_view(), name="device-tags"),
    path("devices/<int:pk>/tags/<int:tag>/", devicetags_views.DeviceTagRemove.as_view(), name="device-tag-remove"),
    path("devices/<int:pk>/lending/", devices_views.DeviceLendingList.as_view(), name="device-lending-list"),
    path("devices/<int:pk>/inventoried/", devices_views.DeviceInventoried.as_view(), name="device-inventoried"),
    path("devices/<int:pk>/bookmark/", devices_views.DeviceBookmark.as_view(), name="device-bookmark"),
    path("devices/<int:pk>/notes/create/", devices_views.NoteCreate.as_view(), name="device-note-create"),
    path("devices/<int:pk>/notes/edit/", devices_views.NoteUpdate.as_view(), name="device-note-edit"),
    path("devices/<int:device>/notes/<int:pk>/delete/", devices_views.NoteDelete.as_view(), name="device-note-delete"),
    path("devices/<int:pk>/pictures/create/", devices_views.PictureCreate.as_view(), name="device-picture-create"),
    path(
        "devices/<int:device>/pictures/<int:pk>/edit/",
        devices_views.PictureUpdate.as_view(),
        name="device-picture-edit",
    ),
    path(
        "devices/<int:device>/pictures/<int:pk>/delete/",
        devices_views.PictureDelete.as_view(),
        name="device-picture-delete",
    ),
    path("devices/lend/", devices_views.DeviceLend.as_view(), name="device-lend"),
    path("devices/lend/<int:pk>/", devices_views.DeviceLend.as_view(), name="device-lend"),
    path("devices/export/csv/", devices_views.ExportCsv.as_view(), name="export-csv"),
    path("devices/return/<int:lending>/", devices_views.DeviceReturn.as_view(), name="device-return"),
    path(
        "devices/public/",
        xframe_options_exempt(devices_views.PublicDeviceListView.as_view()),
        name="public-device-list",
    ),
    path(
        "devices/public/<int:pk>/",
        xframe_options_exempt(devices_views.PublicDeviceDetailView.as_view()),
        name="public-device-detail",
    ),
    path("devices/templates/", devices_views.TemplateList.as_view(), name="template-list"),
    path("devices/templates/add/", devices_views.TemplateCreate.as_view(), name="template-add"),
    path("devices/templates/<int:pk>/edit/", devices_views.TemplateUpdate.as_view(), name="template-edit"),
    path("devices/templates/<int:pk>/delete/", devices_views.TemplateDelete.as_view(), name="template-delete"),
    path("devices/<int:pk>/generate-label/", devices_views.generate_label_pdf, name="device-generate-label"),
    path(
        "devices/<int:pk>/generate-protocol/<str:purpose>/",
        devices_views.generate_device_protocol,
        name="device-generate-protocol",
    ),

    path("types/", devicetypes_views.TypeList.as_view(), name="type-list"),
    path("types/add/", devicetypes_views.TypeCreate.as_view(), name="type-add"),
    path("types/<int:pk>/", devicetypes_views.TypeDetail.as_view(), name="type-detail"),
    path("types/<int:pk>/edit/", devicetypes_views.TypeUpdate.as_view(), name="type-edit"),
    path("types/<int:pk>/delete/", devicetypes_views.TypeDelete.as_view(), name="type-delete"),
    path("types/<int:oldpk>/merge/<int:newpk>/", devicetypes_views.TypeMerge.as_view(), name="type-merge"),
    path("types/attribute/add/", devicetypes_views.TypeAttributeCreate.as_view(), name="typeattribute-add"),
    path("types/attribute/<int:pk>/edit/", devicetypes_views.TypeAttributeUpdate.as_view(), name="typeattribute-edit"),
    path(
        "types/attribute/<int:pk>/delete/", devicetypes_views.TypeAttributeDelete.as_view(), name="typeattribute-delete"
    ),

    path("rooms/", locations_views.RoomList.as_view(), name="room-list"),
    path("rooms/add/", locations_views.RoomCreate.as_view(), name="room-add"),
    path("rooms/<int:pk>/", locations_views.RoomDetail.as_view(), name="room-detail"),
    path("rooms/<int:pk>/edit/", locations_views.RoomUpdate.as_view(), name="room-edit"),
    path("rooms/<int:pk>/delete/", locations_views.RoomDelete.as_view(), name="room-delete"),
    path("rooms/<int:oldpk>/merge/<int:newpk>/", locations_views.RoomMerge.as_view(), name="room-merge"),

    path("buildings/", locations_views.BuildingList.as_view(), name="building-list"),
    path("buildings/add/", locations_views.BuildingCreate.as_view(), name="building-add"),
    path("buildings/<int:pk>/", locations_views.BuildingDetail.as_view(), name="building-detail"),
    path("buildings/<int:pk>/edit/", locations_views.BuildingUpdate.as_view(), name="building-edit"),
    path("buildings/<int:pk>/delete/", locations_views.BuildingDelete.as_view(), name="building-delete"),
    path("buildings/<int:oldpk>/merge/<int:newpk>/", locations_views.BuildingMerge.as_view(), name="building-merge"),

    path("manufacturers/", devices_views.ManufacturerList.as_view(), name="manufacturer-list"),
    path("manufacturers/add/", devices_views.ManufacturerCreate.as_view(), name="manufacturer-add"),
    path("manufacturers/<int:pk>/", devices_views.ManufacturerDetail.as_view(), name="manufacturer-detail"),
    path("manufacturers/<int:pk>/edit/", devices_views.ManufacturerUpdate.as_view(), name="manufacturer-edit"),
    path("manufacturers/<int:pk>/delete/", devices_views.ManufacturerDelete.as_view(), name="manufacturer-delete"),
    path(
        "manufacturers/<int:oldpk>/merge/<int:newpk>/",
        devices_views.ManufacturerMerge.as_view(),
        name="manufacturer-merge",
    ),

    path("devicegroups/", devicegroups_views.DevicegroupList.as_view(), name="devicegroup-list"),
    path("devicegroups/add/", devicegroups_views.DevicegroupCreate.as_view(), name="devicegroup-add"),
    path("devicegroups/<int:pk>/", devicegroups_views.DevicegroupDetail.as_view(), name="devicegroup-detail"),
    path("devicegroups/<int:pk>/edit/", devicegroups_views.DevicegroupUpdate.as_view(), name="devicegroup-edit"),
    path("devicegroups/<int:pk>/delete/", devicegroups_views.DevicegroupDelete.as_view(), name="devicegroup-delete"),

    path("devicetags/", devicetags_views.DevicetagList.as_view(), name="devicetag-list"),
    path("devicetags/add/", devicetags_views.DevicetagCreate.as_view(), name="devicetag-add"),
    path("devicetags/<int:pk>/edit/", devicetags_views.DevicetagUpdate.as_view(), name="devicetag-edit"),
    path("devicetags/<int:pk>/delete/", devicetags_views.DevicetagDelete.as_view(), name="devicetag-delete"),

    path("sections/", locations_views.SectionList.as_view(), name="section-list"),
    path("sections/add/", locations_views.SectionCreate.as_view(), name="section-add"),
    path("sections/<int:pk>/", locations_views.SectionDetail.as_view(), name="section-detail"),
    path("sections/<int:pk>/edit/", locations_views.SectionUpdate.as_view(), name="section-edit"),
    path("sections/<int:pk>/delete/", locations_views.SectionDelete.as_view(), name="section-delete"),
    path("sections/<int:oldpk>/merge/<int:newpk>/", locations_views.SectionMerge.as_view(), name="section-merge"),

    path("departments/", users_views.DepartmentList.as_view(), name="department-list"),
    path("departments/add/", users_views.DepartmentCreate.as_view(), name="department-add"),
    path("departments/<int:pk>/", users_views.DepartmentDetail.as_view(), name="department-detail"),
    path("departments/<int:pk>/edit/", users_views.DepartmentUpdate.as_view(), name="department-edit"),
    path("departments/<int:pk>/adduser/", users_views.DepartmentAddUser.as_view(), name="department-add-user"),

lagerregal/devicegroups/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from reversion import revisions as reversion

from lagerregal.users.models import Department


@reversion.register()
class Devicegroup(models.Model):
    name = models.CharField(max_length=200)
    department = models.ForeignKey(Department, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Device Group")
        verbose_name_plural = _("Device Groups")
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("devicegroup-detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("devicegroup-edit", kwargs={"pk": self.pk})

lagerregal/users/models.py
import logging
import re
from datetime import date

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from lagerregal import utils
from lagerregal.locations.models import Room

try:
    from django_auth_ldap.backend import populate_user
    receive_populate_user = receiver(populate_user)
except ImportError:
    def receive_populate_user(fn):
        return fn


class Lageruser(AbstractUser):
    language = models.CharField(
        max_length=10, null=True, blank=True, choices=settings.LANGUAGES, default=settings.LANGUAGES[0][0]
    )
    avatar = models.ImageField(upload_to=utils.get_file_location, blank=True, null=True)
    expiration_date = models.DateField(null=True, blank=True)

    departments = models.ManyToManyField(
        "users.Department", blank=True, through="users.DepartmentUser", related_name="members"
    )

    def __str__(self):
        if self.first_name != "" and self.last_name != "":
            return f"{self.first_name} {self.last_name}"
        else:
            return self.username

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")
        ordering = ["username"]

    def get_absolute_url(self):
        return reverse("userprofile", kwargs={"pk": self.pk})

    def clean(self):
        # initial ldap population returns a positive int as string
        # will be set correctly later by populate_ldap_user() / ldapimport cmd
        self.expiration_date = None

    @staticmethod
    def users_from_departments(departments=[]):
        if len(departments) == 0:
            return Lageruser.objects.filter(is_active=True)
        return Lageruser.objects.filter(departments__in=departments, is_active=True)


@receive_populate_user
def populate_ldap_user(sender, signal, user, ldap_user, **kwargs):
    """
    this signal is sent after the user object has been created, to override/add specific fields

    see: https://pythonhosted.org/django-auth-ldap/users.html
    """
    if settings.DEBUG:
        logger = logging.getLogger("django_auth_ldap")
        logger.addHandler(logging.StreamHandler())
        logger.setLevel(logging.DEBUG)

    if "accountExpires" in ldap_user.attrs:
        expiration_date = utils.convert_ad_accountexpires(int(ldap_user.attrs["accountExpires"][0]))
        user.expiration_date = expiration_date

        if user.expiration_date and user.expiration_date < date.today():
            user.is_active = False

    auth_ldap_department_regex = getattr(settings, "AUTH_LDAP_DEPARTMENT_REGEX", None)
    if auth_ldap_department_regex is not None:
        auth_ldap_department_field = getattr(settings, "AUTH_LDAP_DEPARTMENT_REGEX", None)
        if auth_ldap_department_field:
            fullname = ldap_user.attrs["distinguishedname"][0]
            match = re.compile(auth_ldap_department_regex).search(fullname)
            if match:
                department_name = match.group(1)
                try:
                    department = Department.objects.get(name=department_name)
                except Exception:
                    department = Department(name=department_name)
                    department.save()
                # departments.all() needs an id
                # so we save a newly created user object first
                if user._state.adding:
                    user.save()
                if department not in user.departments.all():
                    DepartmentUser.objects.get_or_create(user=user, department=department, role="m")

    user.save()


class Department(models.Model):
    name = models.CharField(max_length=40, unique=True)
    short_name = models.CharField(max_length=6, null=True, blank=True)
    storage_room = models.ForeignKey(Room, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Department")
        verbose_name_plural = _("Departments")
        ordering = ["name"]
        permissions = (
            ("add_department_user", _("Can add a User to a Department")),
            ("delete_department_user", _("Can remove a User from a Department")),
        )


class DepartmentUser(models.Model):
    user = models.ForeignKey(Lageruser, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    role = models.CharField(choices=(("a", _("Admin")), ("m", _("Member"))), default="a", max_length=1)
    member_since = models.DateTimeField(auto_now_add=True)

lagerregal/devicetags/forms.py
from django import forms

from lagerregal.devicetags.models import Devicetag
from lagerregal.utils import Select2MultipleWidget


class TagForm(forms.ModelForm):
    class Meta:
        model = Devicetag
        exclude = ["devices"]


class DeviceTagForm(forms.Form):
    error_css_class = "has-error"
    tags = forms.ModelMultipleChoiceField(
        Devicetag.objects.all(),
        widget=Select2MultipleWidget(attrs={"data-token-separators": '[",", " "]'}),
    )

lagerregal/devicetypes/forms.py
from django import forms

from lagerregal.devicetypes.models import Type


class TypeForm(forms.ModelForm):
    error_css_class = "has-error"
    extra_fieldcount = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Type
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        if "data" in kwargs:
            extra_fields = kwargs["data"]["extra_fieldcount"]
        else:
            extra_fields = 1

        super().__init__(*args, **kwargs)
        self.fields["extra_fieldcount"].initial = extra_fields

        for index in range(int(extra_fields)):
            # generate extra fields in the number specified via extra_fields
            self.fields[f"extra_field_{index}"] = forms.CharField(
                label="Extra Attribute",
                widget=forms.TextInput(attrs={"class": "extra_attribute form-control"}),
                required=False,
            )

lagerregal/users/forms.py
from django import forms

from lagerregal.users.models import DepartmentUser
from lagerregal.users.models import Lageruser


class AvatarForm(forms.ModelForm):
    error_css_class = "has-error"
    avatar_clear = forms.BooleanField(required=False)

    class Meta:
        model = Lageruser
        fields = ["avatar"]
        widgets = {"avatar": forms.FileInput()}


class DepartmentAddUserForm(forms.ModelForm):
    error_css_class = "has-error"

    class Meta:
        model = DepartmentUser
        widgets = {"department": forms.HiddenInput()}
        fields = "__all__"

lagerregal/templates/users/department_detail.html
{% extends "base.html" %}
{% load devicetags %}
{% load i18n %}
{% load usertags %}

{% block title %}{{ department.name }}{% endblock %}

{% block pullright %}
    {% has_perm 'users.add_department_user' user department as can_add_department_user %}
    {% if can_add_department_user %}
        <a href="{% url "department-add-user" department.id %}" id="adduserbutton" class="btn btn-primary">
            <i class="fa fa-plus"></i> {% trans "Add User" %}
        </a>
    {% endif %}
    {% if perms.users.change_department %}
        {% editbutton "department-edit" object.id %}
    {% endif %}
    {% if can_delete %}
        {% deletebutton "department-delete" object.id %}
    {% endif %}
{% endblock %}

{% block content %}
    <table class="table table-bordered">
        <tbody>
            <tr>
                <td class="col-1"><b>Storage Room:</b></td>
                <td class="col-1">{{ object.storage_room }}</td>
            </tr>
        </tbody>
    </table>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th class="col-1">{%  trans "User" %}</th>
                <th class="col-1">{% trans "Role" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for member in department_users %}
                <tr>
                    <td><a href="{% url 'userprofile' member.user.id %}">{{member.user}}</a></td>
                    <td>{{ member.get_role_display }}
                        {% if user != member.user %}
                            {% has_perm 'users.add_department_user' user department as can_add_department_user %}
                            {% if can_add_department_user %}
                                <a href="{% url "department-remove-user" member.id %}" class="btn-close">
                                    <span aria-hidden="true">&times;</span><span class="sr-only">Remove from Department</span>
                                </a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

lagerregal/templates/users/department_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Departments" %}{% endblock %}

{% block header %}
    {% trans "Departments" %}
{% endblock %}

{% block pullright %}
    {% if perms.users.add_department %}
        <a href="{% url 'department-add' %}" class="btn btn-primary">
            <i class="fa fa-plus"></i> {% trans "Add Department" %}
        </a>
    {% endif %}
    {% include "snippets/widgets/filter_dropdown.html" with field=viewform.sorting %}
    {% include "snippets/filterform.html" %}
{% endblock %}

{% block content %}
    {% include "snippets/pagination.html" %}
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>{% trans "Name" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for department in department_list %}
                <tr>
                    <td><a href="{% url 'department-detail' department.id %}">{{ department.name|default:_("(None)") }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% include "snippets/pagination.html" %}
{% endblock %}

lagerregal/templates/users/settings.html
{% extends "base.html" %}
{% load i18n %}
{% load devicetags %}

{% block title %}{% trans "Settings" %}{% endblock %}

{% block header %}
    {% trans "Settings" %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h3>{% trans "Language" %}</h3>

            <form action="{% url 'usersettings' %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <select name="language" class="form-control">
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == user.language %}
                                    selected="selected"{% endif %}>{{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="text-end">
                    <button type="submit" class="btn btn-secondary">{% trans "Set Language" %}</button>
                </div>
            </form>
            <div class="clearfix"></div>
            <hr>

            <h3>{% trans "Avatar" %}</h3>
            <form enctype="multipart/form-data" action="{% url 'usersettings' %}" method="post">
                {% csrf_token %}
                {% if user.avatar %}
                    <div class="row">
                        <div class="col-sm-6 col-md-6 pull-right">
                            <a data-bs-toggle="modal" data-bs-target="#avatarModal" class="thumbnail">
                                <img src="{{ user.avatar.url }}" alt="Avatar" class="img-fluid">
                            </a>
                        </div>
                    </div>
                    <div class="text-end">
                        <input id="id_avatar_clear" name="avatar_clear" type="checkbox"/>
                        <label for="avatar-clear_id">{% trans "Remove" %}</label>
                    </div>
                    <div class="clearfix"></div>
                {% endif %}
                <div class="mb-3 row {{ avatarform.avatar.css_classes }}">
                    <div class="col-lg-8 col-lg-offset-4">
                        {{ avatarform.avatar|add_class:'form-control' }}
                        {% if avatarform.avatar.errors %}
                            <p class="text-danger">
                                {% for error in avatarform.avatar.errors %}{{ error }}, {% endfor %}
                            </p>
                        {% endif %}
                        {% if avatarform.avatar.help_text %}
                            <p class="text-muted">
                                {{ avatarform.avatar.help_text }}
                            </p>
                        {% endif %}
                    </div>
                </div>
                <div class="text-end">
                    <button type="submit" class="btn btn-secondary">{% trans "Upload" %}</button>
                </div>
            </form>
        </div>
    </div>

    {% if user.avatar %}
        {% include "snippets/modals/avatarView.html" with modalname="avatarModal" avatarpath=user.avatar.url %}
    {% endif %}
{% endblock %}

lagerregal/templates/users/transfer_ownershop.html
{% extends "base.html" %}
{% load devicetags %}
{% load i18n %}

{% block title %}
    {% blocktrans %}Transfer ownerships from {{ old_user.name }} to {{ new_user.name }}{% endblocktrans %}
{% endblock %}


{% block header %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="alert-info alert">
                {% get_verbose_name old_user as verbose_name %}
                {% blocktrans %}Do you really want to transfer the {{ verbose_name }} ownerships from {{ old_user }} to {{ new_user }}?{% endblocktrans %}
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <a href="{{ old_user.get_absolute_url }}" class="btn btn-secondary">{% trans "No" %}</a>
                <input type="submit" value="Yes" class="btn btn-primary"/>
            </form>
        </div>
    </div>
{% endblock %}

lagerregal/templates/users/user_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Users" %}{% endblock %}

{% block header %}
    {% trans "Users" %}
{% endblock %}

{% block pullright %}
    {% include "snippets/widgets/filter_dropdown.html" with field=filterform.department %}
    {% include "snippets/filterform.html" %}
{% endblock %}

{% block content %}
    {% include "snippets/pagination.html" %}
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Username" %}</th>
                <th>{% trans "Staff" %}</th>
                <th>{% trans "Admin" %}</th>
                <th>{% trans "Last Login" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for user in user_list %}
                <tr>
                    <td><a href="{% url 'userprofile' user.id %}">{{ user }}</a></td>
                    <td>{{ user.username }}</td>
                    <td>
                        {% if user.is_staff %}
                            <i class="fa fa-check-circle text-success"></i>
                        {% else %}
                            <i class="fa fa-exclamation-circle text-danger"></i>
                        {% endif %}
                    </td>
                    <td>
                        {% if user.is_superuser %}
                            <i class="fa fa-check-circle text-success"></i>
                        {% else %}
                            <i class="fa fa-exclamation-circle text-danger"></i>
                        {% endif %}
                    </td>
                    <td>{{ user.last_login }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include "snippets/pagination.html" %}
{% endblock %}