lagerregal/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include
from django.urls import path
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve
from favicon import conf
from rest_framework.urlpatterns import format_suffix_patterns

from lagerregal.api import views as api_views
from lagerregal.devicegroups import views as devicegroups_views
from lagerregal.devices import ajax as devices_ajax
from lagerregal.devices import views as devices_views
from lagerregal.devicetags import views as devicetags_views
from lagerregal.devicetypes import ajax as devicetypes_ajax
from lagerregal.devicetypes import views as devicetypes_views
from lagerregal.history import views as history_views
from lagerregal.locations import views as locations_views
from lagerregal.main import ajax as main_ajax
from lagerregal.main import views as main_views
from lagerregal.users import views as users_views

urlpatterns = [
    path("", login_required(main_views.Home.as_view()), name="home"),

    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("search/", devices_views.Search.as_view(), name="search"),

    path("devices/", devices_views.DeviceList.as_view(), name="device-list"),
    path("devices/add/", devices_views.DeviceCreate.as_view(), name="device-add"),
    path("devices/add/template/<int:templateid>/", devices_views.DeviceCreate.as_view(), name="device-add"),
    path("devices/add/copy/<int:copyid>/", devices_views.DeviceCreate.as_view(), name="device-add-copy"),
    path("devices/<int:pk>/", devices_views.DeviceDetail.as_view(), name="device-detail"),
    path("devices/<int:pk>/edit/", devices_views.DeviceUpdate.as_view(), name="device-edit"),
    path("devices/<int:pk>/delete/", devices_views.DeviceDelete.as_view(), name="device-delete"),
    path("devices/<int:pk>/archive/", devices_views.DeviceArchive.as_view(), name="device-archive"),
    path("devices/<int:pk>/trash/", devices_views.DeviceTrash.as_view(), name="device-trash"),
    path("devices/<int:pk>/storage/", devices_views.DeviceStorage.as_view(), name="device-storage"),
    path("devices/<int:pk>/mail/", devices_views.DeviceMail.as_view(), name="device-mail"),
    path("devices/<int:pk>/tags/", devicetags_views.DeviceTags.as_view(), name="device-tags"),
    path("devices/<int:pk>/tags/<int:tag>/", devicetags_views.DeviceTagRemove.as_view(), name="device-tag-remove"),
    path("devices/<int:pk>/lending/", devices_views.DeviceLendingList.as_view(), name="device-lending-list"),
    path("devices/<int:pk>/inventoried/", devices_views.DeviceInventoried.as_view(), name="device-inventoried"),
    path("devices/<int:pk>/bookmark/", devices_views.DeviceBookmark.as_view(), name="device-bookmark"),
    path("devices/<int:pk>/notes/create/", devices_views.NoteCreate.as_view(), name="device-note-create"),
    path("devices/<int:pk>/notes/edit/", devices_views.NoteUpdate.as_view(), name="device-note-edit"),
    path("devices/<int:device>/notes/<int:pk>/delete/", devices_views.NoteDelete.as_view(), name="device-note-delete"),
    path("devices/<int:pk>/pictures/create/", devices_views.PictureCreate.as_view(), name="device-picture-create"),
    path(
        "devices/<int:device>/pictures/<int:pk>/edit/",
        devices_views.PictureUpdate.as_view(),
        name="device-picture-edit",
    ),
    path(
        "devices/<int:device>/pictures/<int:pk>/delete/",
        devices_views.PictureDelete.as_view(),
        name="device-picture-delete",
    ),
    path("devices/lend/", devices_views.DeviceLend.as_view(), name="device-lend"),
    path("devices/lend/<int:pk>/", devices_views.DeviceLend.as_view(), name="device-lend"),
    path("devices/export/csv/", devices_views.ExportCsv.as_view(), name="export-csv"),
    path("devices/return/<int:lending>/", devices_views.DeviceReturn.as_view(), name="device-return"),
    path(
        "devices/public/",
        xframe_options_exempt(devices_views.PublicDeviceListView.as_view()),
        name="public-device-list",
    ),
    path(
        "devices/public/<int:pk>/",
        xframe_options_exempt(devices_views.PublicDeviceDetailView.as_view()),
        name="public-device-detail",
    ),
    path("devices/templates/", devices_views.TemplateList.as_view(), name="template-list"),
    path("devices/templates/add/", devices_views.TemplateCreate.as_view(), name="template-add"),
    path("devices/templates/<int:pk>/edit/", devices_views.TemplateUpdate.as_view(), name="template-edit"),
    path("devices/templates/<int:pk>/delete/", devices_views.TemplateDelete.as_view(), name="template-delete"),
    path("devices/<int:pk>/generate-label/", devices_views.generate_label_pdf, name="device-generate-label"),
    path(
        "devices/<int:pk>/generate-protocol/<str:purpose>/",
        devices_views.generate_device_protocol,
        name="device-generate-protocol",
    ),

    path("types/", devicetypes_views.TypeList.as_view(), name="type-list"),
    path("types/add/", devicetypes_views.TypeCreate.as_view(), name="type-add"),
    path("types/<int:pk>/", devicetypes_views.TypeDetail.as_view(), name="type-detail"),
    path("types/<int:pk>/edit/", devicetypes_views.TypeUpdate.as_view(), name="type-edit"),
    path("types/<int:pk>/delete/", devicetypes_views.TypeDelete.as_view(), name="type-delete"),
    path("types/<int:oldpk>/merge/<int:newpk>/", devicetypes_views.TypeMerge.as_view(), name="type-merge"),
    path("types/attribute/add/", devicetypes_views.TypeAttributeCreate.as_view(), name="typeattribute-add"),
    path("types/attribute/<int:pk>/edit/", devicetypes_views.TypeAttributeUpdate.as_view(), name="typeattribute-edit"),
    path(
        "types/attribute/<int:pk>/delete/", devicetypes_views.TypeAttributeDelete.as_view(), name="typeattribute-delete"
    ),

    path("rooms/", locations_views.RoomList.as_view(), name="room-list"),
    path("rooms/add/", locations_views.RoomCreate.as_view(), name="room-add"),
    path("rooms/<int:pk>/", locations_views.RoomDetail.as_view(), name="room-detail"),
    path("rooms/<int:pk>/edit/", locations_views.RoomUpdate.as_view(), name="room-edit"),
    path("rooms/<int:pk>/delete/", locations_views.RoomDelete.as_view(), name="room-delete"),
    path("rooms/<int:oldpk>/merge/<int:newpk>/", locations_views.RoomMerge.as_view(), name="room-merge"),

    path("buildings/", locations_views.BuildingList.as_view(), name="building-list"),
    path("buildings/add/", locations_views.BuildingCreate.as_view(), name="building-add"),
    path("buildings/<int:pk>/", locations_views.BuildingDetail.as_view(), name="building-detail"),
    path("buildings/<int:pk>/edit/", locations_views.BuildingUpdate.as_view(), name="building-edit"),
    path("buildings/<int:pk>/delete/", locations_views.BuildingDelete.as_view(), name="building-delete"),
    path("buildings/<int:oldpk>/merge/<int:newpk>/", locations_views.BuildingMerge.as_view(), name="building-merge"),

    path("manufacturers/", devices_views.ManufacturerList.as_view(), name="manufacturer-list"),
    path("manufacturers/add/", devices_views.ManufacturerCreate.as_view(), name="manufacturer-add"),
    path("manufacturers/<int:pk>/", devices_views.ManufacturerDetail.as_view(), name="manufacturer-detail"),
    path("manufacturers/<int:pk>/edit/", devices_views.ManufacturerUpdate.as_view(), name="manufacturer-edit"),
    path("manufacturers/<int:pk>/delete/", devices_views.ManufacturerDelete.as_view(), name="manufacturer-delete"),
    path(
        "manufacturers/<int:oldpk>/merge/<int:newpk>/",
        devices_views.ManufacturerMerge.as_view(),
        name="manufacturer-merge",
    ),

    path("devicegroups/", devicegroups_views.DevicegroupList.as_view(), name="devicegroup-list"),
    path("devicegroups/add/", devicegroups_views.DevicegroupCreate.as_view(), name="devicegroup-add"),
    path("devicegroups/<int:pk>/", devicegroups_views.DevicegroupDetail.as_view(), name="devicegroup-detail"),
    path("devicegroups/<int:pk>/edit/", devicegroups_views.DevicegroupUpdate.as_view(), name="devicegroup-edit"),
    path("devicegroups/<int:pk>/delete/", devicegroups_views.DevicegroupDelete.as_view(), name="devicegroup-delete"),

    path("devicetags/", devicetags_views.DevicetagList.as_view(), name="devicetag-list"),
    path("devicetags/add/", devicetags_views.DevicetagCreate.as_view(), name="devicetag-add"),
    path("devicetags/<int:pk>/edit/", devicetags_views.DevicetagUpdate.as_view(), name="devicetag-edit"),
    path("devicetags/<int:pk>/delete/", devicetags_views.DevicetagDelete.as_view(), name="devicetag-delete"),

    path("sections/", locations_views.SectionList.as_view(), name="section-list"),
    path("sections/add/", locations_views.SectionCreate.as_view(), name="section-add"),
    path("sections/<int:pk>/", locations_views.SectionDetail.as_view(), name="section-detail"),
    path("sections/<int:pk>/edit/", locations_views.SectionUpdate.as_view(), name="section-edit"),
    path("sections/<int:pk>/delete/", locations_views.SectionDelete.as_view(), name="section-delete"),
    path("sections/<int:oldpk>/merge/<int:newpk>/", locations_views.SectionMerge.as_view(), name="section-merge"),

    path("departments/", users_views.DepartmentList.as_view(), name="department-list"),
    path("departments/add/", users_views.DepartmentCreate.as_view(), name="department-add"),
    path("departments/<int:pk>/", users_views.DepartmentDetail.as_view(), name="department-detail"),
    path("departments/<int:pk>/edit/", users_views.DepartmentUpdate.as_view(), name="department-edit"),
    path("departments/<int:pk>/adduser/", users_views.DepartmentAddUser.as_view(), name="department-add-user"),

lagerregal/devicegroups/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from reversion import revisions as reversion

from lagerregal.users.models import Department


@reversion.register()
class Devicegroup(models.Model):
    name = models.CharField(max_length=200)
    department = models.ForeignKey(Department, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Device Group")
        verbose_name_plural = _("Device Groups")
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("devicegroup-detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("devicegroup-edit", kwargs={"pk": self.pk})

lagerregal/devicetags/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from lagerregal.devices.models import Device


# Create your models here.
class Devicetag(models.Model):
    name = models.CharField(max_length=200, unique=True)
    devices = models.ManyToManyField(Device, related_name="tags")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Device Tag")
        verbose_name_plural = _("Devicegtag")
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("devicetag-edit", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("devicetag-edit", kwargs={"pk": self.pk})

lagerregal/devicetypes/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from reversion import revisions as reversion


@reversion.register()
class Type(models.Model):
    name = models.CharField(_("Name"), max_length=200, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Type")
        verbose_name_plural = _("Types")
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("type-detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("type-edit", kwargs={"pk": self.pk})


@reversion.register()
class TypeAttribute(models.Model):
    devicetype = models.ForeignKey(Type, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    regex = models.CharField(max_length=500, blank=True, null=True)

    class Meta:
        verbose_name = _("Type Attribute")
        verbose_name_plural = _("Type Attributes")

    def get_absolute_url(self):
        return reverse("type-detail", kwargs={"pk": self.devicetype.pk})

    def __str__(self):
        return self.name


@reversion.register()
class TypeAttributeValue(models.Model):
    typeattribute = models.ForeignKey(TypeAttribute, on_delete=models.CASCADE)
    value = models.CharField(max_length=400)
    device = models.ForeignKey("devices.Device", on_delete=models.CASCADE)

    class Meta:
        verbose_name = _("Type Attribute value")
        verbose_name_plural = _("Type Attribute values")
        unique_together = [["device", "typeattribute"]]

    def __str__(self):
        return self.value

lagerregal/locations/models.py
import reversion
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Section(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Section")
        verbose_name_plural = _("Sections")
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("section-detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("section-edit", kwargs={"pk": self.pk})


@reversion.register()
class Building(models.Model):
    name = models.CharField(_("Name"), max_length=200, unique=True)
    street = models.CharField(_("Street"), max_length=100, blank=True)
    number = models.CharField(_("Number"), max_length=30, blank=True)
    zipcode = models.CharField(_("ZIP Code"), max_length=5, blank=True)
    city = models.CharField(_("City"), max_length=100, blank=True)
    state = models.CharField(_("State"), max_length=100, blank=True)
    country = models.CharField(_("Country"), max_length=100, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Building")
        verbose_name_plural = _("Buildings")
        ordering = ["name"]
        db_table = "devices_building"

    def get_absolute_url(self):
        return reverse("building-detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("building-edit", kwargs={"pk": self.pk})


@reversion.register()
class Room(models.Model):
    name = models.CharField(_("Name"), max_length=200)
    building = models.ForeignKey(Building, null=True, on_delete=models.SET_NULL)
    section = models.ForeignKey(Section, null=True, on_delete=models.SET_NULL, related_name="rooms", blank=True)

    def __str__(self):
        if self.building:
            return self.name + " (" + str(self.building) + ")"
        else:
            return self.name

    class Meta:
        verbose_name = _("Room")
        verbose_name_plural = _("Rooms")
        ordering = ["name"]
        db_table = "devices_room"

    def get_absolute_url(self):
        return reverse("room-detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("room-edit", kwargs={"pk": self.pk})

lagerregal/devicetags/forms.py
from django import forms

from lagerregal.devicetags.models import Devicetag
from lagerregal.utils import Select2MultipleWidget


class TagForm(forms.ModelForm):
    class Meta:
        model = Devicetag
        exclude = ["devices"]


class DeviceTagForm(forms.Form):
    error_css_class = "has-error"
    tags = forms.ModelMultipleChoiceField(
        Devicetag.objects.all(),
        widget=Select2MultipleWidget(attrs={"data-token-separators": '[",", " "]'}),
    )

lagerregal/devicetypes/forms.py
from django import forms

from lagerregal.devicetypes.models import Type


class TypeForm(forms.ModelForm):
    error_css_class = "has-error"
    extra_fieldcount = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Type
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        if "data" in kwargs:
            extra_fields = kwargs["data"]["extra_fieldcount"]
        else:
            extra_fields = 1

        super().__init__(*args, **kwargs)
        self.fields["extra_fieldcount"].initial = extra_fields

        for index in range(int(extra_fields)):
            # generate extra fields in the number specified via extra_fields
            self.fields[f"extra_field_{index}"] = forms.CharField(
                label="Extra Attribute",
                widget=forms.TextInput(attrs={"class": "extra_attribute form-control"}),
                required=False,
            )

lagerregal/users/forms.py
from django import forms

from lagerregal.users.models import DepartmentUser
from lagerregal.users.models import Lageruser


class AvatarForm(forms.ModelForm):
    error_css_class = "has-error"
    avatar_clear = forms.BooleanField(required=False)

    class Meta:
        model = Lageruser
        fields = ["avatar"]
        widgets = {"avatar": forms.FileInput()}


class DepartmentAddUserForm(forms.ModelForm):
    error_css_class = "has-error"

    class Meta:
        model = DepartmentUser
        widgets = {"department": forms.HiddenInput()}
        fields = "__all__"

lagerregal/templates/base.html
{% load i18n static usertags %}<!DOCTYPE html>
<html lang="{{ user.language|default:"en" }}">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Security-Policy" content="{% block CSP %}default-src 'self'; img-src 'self' data:; frame-src 'self' blob:{% endblock %}">
    <title>{% block title %}{% endblock %} &middot; {{ SITE_NAME }}</title>
    <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "select2/dist/css/select2.min.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <link rel="stylesheet" href="{% static "jquery-ui-dist/jquery-ui.min.css" %}">
    <link rel="stylesheet" href="{% static "font-awesome/css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "datatables.net-bs4/css/dataTables.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "css/clippy.css" %}">

    <link rel="shortcut icon" href="{% static "images/favicon.ico" %}">
    <link rel="apple-touch-icon" href="{% static "images/apple-touch-icon.png" %}">
</head>
<body class="{% block body_class%}{% endblock %}">
{% if not nochrome %}
<header class="navbar navbar-expand-lg navbar-dark bg-black border-bottom sticky-top px-3 mb-3">
    <a class="navbar-brand" href="/"><i class="fa fa-archive"></i> {{ SITE_NAME }}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="{% trans 'Toggle navigation' %}">
        <i class="navbar-toggler-icon"></i>
    </button>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbarNav">
        <nav class="me-auto">
            <ul class="nav navbar-nav">
                <li class="nav-item dropdown">
                    <a href="{% url 'device-list' %}" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                        {% trans "Devices" %}
                    </a>
                    <div class="dropdown-menu">
                        {% if perms.devices.view_device %}
                            <a href="{% url 'device-list' %}" class="dropdown-item">{% trans "Devices" %}</a>
                        {% endif %}
                        {% if perms.devicetypes.view_type %}
                            <a href="{% url 'type-list' %}" class="dropdown-item">{% trans "Device Types" %}</a>
                        {% endif %}
                        {% if perms.devices.view_manufacturer %}
                            <a href="{% url 'manufacturer-list' %}" class="dropdown-item">{% trans "Manufacturers" %}</a>
                        {% endif %}
                        {% if perms.devicegroups.view_devicegroup %}
                            <a href="{% url 'devicegroup-list' %}" class="dropdown-item">{% trans "Device Groups" %}</a>
                        {% endif %}
                        <a href="{% url 'public-device-list' %}" class="dropdown-item">{% trans "Public Devices" %}</a>
                    </div>
                </li>
                {% if perms.devices.view_room or perms.devices.view_building or perms.locations.view_section %}
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">{% trans "Locations" %}</a>

                        <div class="dropdown-menu">
                            {% if perms.devices.view_room %}
                                <a href="{% url 'room-list' %}" class="dropdown-item">{% trans "Rooms" %}</a>
                            {% endif %}
                            {% if perms.devices.view_building %}
                                <a href="{% url 'building-list' %}" class="dropdown-item">{% trans "Buildings" %}</a>
                            {% endif %}
                            {% if perms.locations.view_section %}
                                <a href="{% url 'section-list' %}" class="dropdown-item">{% trans "Sections" %}</a>
                            {% endif %}
                        </div>
                    </li>
                {% endif %}
                {% if perms.users.view_lageruser or perms.users.view_department or perms.devicetags.view_devicetags %}
                    <li class="nav-item dropdown">
                        <a href="{% url 'device-list' %}" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            {% trans "Manage" %}
                        </a>
                        <div class="dropdown-menu">
                            {% if perms.users.view_lageruser %}
                                <a href="{% url 'user-list' %}" class="dropdown-item">{% trans "Users" %}</a>
                            {% endif %}
                            {% if perms.users.view_department %}
                                <a href="{% url 'department-list' %}" class="dropdown-item">{% trans "Departments" %}</a>
                            {% endif %}
                            {% if perms.devicetags.view_devicetag %}
                                <a href="{% url 'devicetag-list' %}" class="dropdown-item">{% trans "Device Tags" %}</a>
                            {% endif %}
                        </div>
                    </li>
                {% endif %}
            </ul>
        </nav>

        {% if perms.devices.view_device %}
            <form method="post" action="{% url 'device-list' %}" class="form-inline my-2 my-lg-0 mx-lg-1">
                {% csrf_token %}
                <input id="id_namemodifier" name="namemodifier" type="hidden" value="icontains">
                <div class="input-group">
                    <input id="id_deviceid" name="deviceid" placeholder="{% trans 'Jump to ID' %}" type="text" class="form-control">
                    <button type="submit" class="input-group-append btn btn-secondary">
                        <i class="fa fa-rocket"></i>
                    </button>
                </div>
            </form>
            <form method="get" action="{% url 'search' %}" class="form-inline my-2 my-lg-0 mx-lg-1">
                <div class="input-group">
                    <input id="id_searchname" name="searchstring" placeholder="{% trans 'Search for Device' %}" type="text" class="form-control">
                    <button type="submit" class="input-group-append btn btn-secondary">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </form>
        {% endif %}

        <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a href="#" data-bs-toggle="dropdown" class="nav-link dropdown-toggle">
                        {% if user.avatar %}
                            <img class="navbar-avatar rounded" src="{{ user.avatar.url }}">
                        {% endif %}
                        {{ user }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <a href="{% url 'userprofile' %}" class="dropdown-item"><i class="fa fa-user"></i> {% trans "Profile" %}</a>
                        <a href="{% url 'usersettings' %}" class="dropdown-item"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
                        {% if user.is_staff %}
                            <a href="{% url 'admin:index' %}" class="dropdown-item"><i class="fa fa-lock"></i> {% trans "Admin" %}</a>
                        {% endif %}
                        <a href="{% url 'logout' %}" class="dropdown-item"><i class="fa fa-sign-out"></i> {% trans "Logout" %}</a>
                    </div>
                </li>
            {% else %}
                <li id="loginbutton">
                    <a href="{% url 'login' %}" class="btn btn-primary">
                        <i class="fa fa-sign-in"></i> {% trans "Login" %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
</header>
{% endif %}

<div class="container">
    <main>
        {% for message in messages %}
            <p role="alert" class="{{ message|bootstrap_message_classes }}">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="{% trans 'Close' %}"></button>
            </p>
        {% endfor %}
        {% if breadcrumbs %}
            <header class="bg-body-tertiary d-flex justify-content-between align-items-center p-3 mb-3 flex-md-row flex-column">
                <h1 class="h3 m-0 flex-shrink-0">
                    <ol class="breadcrumb p-0 m-0 bg-transparent">
                        {% for crumb in breadcrumbs %}
                            {% if forloop.last or crumb.0 is None %}
                                <li class="breadcrumb-item active">{{ crumb.1 }}</li>
                            {% else %}
                                <li class="breadcrumb-item"><a href="{{ crumb.0 }}">{{ crumb.1 }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ol>
                </h1>
                {% if not nochrome %}
                    <div>{% block pullright %}{% endblock %}</div>
                {% endif %}
            </header>
        {% endif %}

        {% block content %}{% endblock %}
    </main>

    <footer id="footer" class="py-3 mt-5 mb-3 border-top text-end">
        {% trans "powered by" %} <a href="https://git.mpib-berlin.mpg.de/castellum/lagerregal/">Lagerregal</a>
    </footer>
</div>

<script src="{% static "jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "@popperjs/core/dist/umd/popper-lite.min.js" %}"></script>
<script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
<script src="{% static "select2/dist/js/select2.min.js" %}"></script>
<script src="{% static "jquery-ui-dist/jquery-ui.min.js" %}"></script>

<script src="{% static "datatables.net/js/jquery.dataTables.min.js" %}"></script>
<script src="{% static "datatables.net-bs4/js/dataTables.bootstrap4.min.js" %}"></script>

<script src="{% static "timeago/jquery.timeago.js" %}"></script>
{% if user.language != "en" %}
    <script src="{% static "timeago/locales/jquery.timeago.de.js" %}"></script>
{% endif %}

<script src="{% static "js/clippy.min.js" %} "></script>

{% block htmlend %}{% endblock %}

<script src="{% url 'javascript-catalog' %}"></script>
<script src="{% static "js/lagerregal.js" %} "></script>
<script src="{% static "js/widgets.js" %}"></script>

</body>

</html>