lagerregal/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import include
from django.urls import path
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve
from favicon import conf
from rest_framework.urlpatterns import format_suffix_patterns

from lagerregal.api import views as api_views
from lagerregal.devicegroups import views as devicegroups_views
from lagerregal.devices import ajax as devices_ajax
from lagerregal.devices import views as devices_views
from lagerregal.devicetags import views as devicetags_views
from lagerregal.devicetypes import ajax as devicetypes_ajax
from lagerregal.devicetypes import views as devicetypes_views
from lagerregal.history import views as history_views
from lagerregal.locations import views as locations_views
from lagerregal.main import ajax as main_ajax
from lagerregal.main import views as main_views
from lagerregal.users import views as users_views

urlpatterns = [
    path("", login_required(main_views.Home.as_view()), name="home"),

    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("search/", devices_views.Search.as_view(), name="search"),

    path("devices/", devices_views.DeviceList.as_view(), name="device-list"),
    path("devices/add/", devices_views.DeviceCreate.as_view(), name="device-add"),
    path("devices/add/template/<int:templateid>/", devices_views.DeviceCreate.as_view(), name="device-add"),
    path("devices/add/copy/<int:copyid>/", devices_views.DeviceCreate.as_view(), name="device-add-copy"),
    path("devices/<int:pk>/", devices_views.DeviceDetail.as_view(), name="device-detail"),
    path("devices/<int:pk>/edit/", devices_views.DeviceUpdate.as_view(), name="device-edit"),
    path("devices/<int:pk>/delete/", devices_views.DeviceDelete.as_view(), name="device-delete"),
    path("devices/<int:pk>/archive/", devices_views.DeviceArchive.as_view(), name="device-archive"),
    path("devices/<int:pk>/trash/", devices_views.DeviceTrash.as_view(), name="device-trash"),
    path("devices/<int:pk>/storage/", devices_views.DeviceStorage.as_view(), name="device-storage"),
    path("devices/<int:pk>/mail/", devices_views.DeviceMail.as_view(), name="device-mail"),
    path("devices/<int:pk>/tags/", devicetags_views.DeviceTags.as_view(), name="device-tags"),
    path("devices/<int:pk>/tags/<int:tag>/", devicetags_views.DeviceTagRemove.as_view(), name="device-tag-remove"),
    path("devices/<int:pk>/lending/", devices_views.DeviceLendingList.as_view(), name="device-lending-list"),
    path("devices/<int:pk>/inventoried/", devices_views.DeviceInventoried.as_view(), name="device-inventoried"),
    path("devices/<int:pk>/bookmark/", devices_views.DeviceBookmark.as_view(), name="device-bookmark"),
    path("devices/<int:pk>/notes/create/", devices_views.NoteCreate.as_view(), name="device-note-create"),
    path("devices/<int:pk>/notes/edit/", devices_views.NoteUpdate.as_view(), name="device-note-edit"),
    path("devices/<int:device>/notes/<int:pk>/delete/", devices_views.NoteDelete.as_view(), name="device-note-delete"),
    path("devices/<int:pk>/pictures/create/", devices_views.PictureCreate.as_view(), name="device-picture-create"),
    path(
        "devices/<int:device>/pictures/<int:pk>/edit/",
        devices_views.PictureUpdate.as_view(),
        name="device-picture-edit",
    ),
    path(
        "devices/<int:device>/pictures/<int:pk>/delete/",
        devices_views.PictureDelete.as_view(),
        name="device-picture-delete",
    ),
    path("devices/lend/", devices_views.DeviceLend.as_view(), name="device-lend"),
    path("devices/lend/<int:pk>/", devices_views.DeviceLend.as_view(), name="device-lend"),
    path("devices/export/csv/", devices_views.ExportCsv.as_view(), name="export-csv"),
    path("devices/return/<int:lending>/", devices_views.DeviceReturn.as_view(), name="device-return"),
    path(
        "devices/public/",
        xframe_options_exempt(devices_views.PublicDeviceListView.as_view()),
        name="public-device-list",
    ),
    path(
        "devices/public/<int:pk>/",
        xframe_options_exempt(devices_views.PublicDeviceDetailView.as_view()),
        name="public-device-detail",
    ),
    path("devices/templates/", devices_views.TemplateList.as_view(), name="template-list"),
    path("devices/templates/add/", devices_views.TemplateCreate.as_view(), name="template-add"),
    path("devices/templates/<int:pk>/edit/", devices_views.TemplateUpdate.as_view(), name="template-edit"),
    path("devices/templates/<int:pk>/delete/", devices_views.TemplateDelete.as_view(), name="template-delete"),
    path("devices/<int:pk>/generate-label/", devices_views.generate_label_pdf, name="device-generate-label"),
    path(
        "devices/<int:pk>/generate-protocol/<str:purpose>/",
        devices_views.generate_device_protocol,
        name="device-generate-protocol",
    ),

    path("types/", devicetypes_views.TypeList.as_view(), name="type-list"),
    path("types/add/", devicetypes_views.TypeCreate.as_view(), name="type-add"),
    path("types/<int:pk>/", devicetypes_views.TypeDetail.as_view(), name="type-detail"),
    path("types/<int:pk>/edit/", devicetypes_views.TypeUpdate.as_view(), name="type-edit"),
    path("types/<int:pk>/delete/", devicetypes_views.TypeDelete.as_view(), name="type-delete"),
    path("types/<int:oldpk>/merge/<int:newpk>/", devicetypes_views.TypeMerge.as_view(), name="type-merge"),
    path("types/attribute/add/", devicetypes_views.TypeAttributeCreate.as_view(), name="typeattribute-add"),
    path("types/attribute/<int:pk>/edit/", devicetypes_views.TypeAttributeUpdate.as_view(), name="typeattribute-edit"),
    path(
        "types/attribute/<int:pk>/delete/", devicetypes_views.TypeAttributeDelete.as_view(), name="typeattribute-delete"
    ),

    path("rooms/", locations_views.RoomList.as_view(), name="room-list"),
    path("rooms/add/", locations_views.RoomCreate.as_view(), name="room-add"),
    path("rooms/<int:pk>/", locations_views.RoomDetail.as_view(), name="room-detail"),
    path("rooms/<int:pk>/edit/", locations_views.RoomUpdate.as_view(), name="room-edit"),
    path("rooms/<int:pk>/delete/", locations_views.RoomDelete.as_view(), name="room-delete"),
    path("rooms/<int:oldpk>/merge/<int:newpk>/", locations_views.RoomMerge.as_view(), name="room-merge"),

    path("buildings/", locations_views.BuildingList.as_view(), name="building-list"),
    path("buildings/add/", locations_views.BuildingCreate.as_view(), name="building-add"),
    path("buildings/<int:pk>/", locations_views.BuildingDetail.as_view(), name="building-detail"),
    path("buildings/<int:pk>/edit/", locations_views.BuildingUpdate.as_view(), name="building-edit"),
    path("buildings/<int:pk>/delete/", locations_views.BuildingDelete.as_view(), name="building-delete"),
    path("buildings/<int:oldpk>/merge/<int:newpk>/", locations_views.BuildingMerge.as_view(), name="building-merge"),

    path("manufacturers/", devices_views.ManufacturerList.as_view(), name="manufacturer-list"),
    path("manufacturers/add/", devices_views.ManufacturerCreate.as_view(), name="manufacturer-add"),
    path("manufacturers/<int:pk>/", devices_views.ManufacturerDetail.as_view(), name="manufacturer-detail"),
    path("manufacturers/<int:pk>/edit/", devices_views.ManufacturerUpdate.as_view(), name="manufacturer-edit"),
    path("manufacturers/<int:pk>/delete/", devices_views.ManufacturerDelete.as_view(), name="manufacturer-delete"),
    path(
        "manufacturers/<int:oldpk>/merge/<int:newpk>/",
        devices_views.ManufacturerMerge.as_view(),
        name="manufacturer-merge",
    ),

    path("devicegroups/", devicegroups_views.DevicegroupList.as_view(), name="devicegroup-list"),
    path("devicegroups/add/", devicegroups_views.DevicegroupCreate.as_view(), name="devicegroup-add"),
    path("devicegroups/<int:pk>/", devicegroups_views.DevicegroupDetail.as_view(), name="devicegroup-detail"),
    path("devicegroups/<int:pk>/edit/", devicegroups_views.DevicegroupUpdate.as_view(), name="devicegroup-edit"),
    path("devicegroups/<int:pk>/delete/", devicegroups_views.DevicegroupDelete.as_view(), name="devicegroup-delete"),

    path("devicetags/", devicetags_views.DevicetagList.as_view(), name="devicetag-list"),
    path("devicetags/add/", devicetags_views.DevicetagCreate.as_view(), name="devicetag-add"),
    path("devicetags/<int:pk>/edit/", devicetags_views.DevicetagUpdate.as_view(), name="devicetag-edit"),
    path("devicetags/<int:pk>/delete/", devicetags_views.DevicetagDelete.as_view(), name="devicetag-delete"),

    path("sections/", locations_views.SectionList.as_view(), name="section-list"),
    path("sections/add/", locations_views.SectionCreate.as_view(), name="section-add"),
    path("sections/<int:pk>/", locations_views.SectionDetail.as_view(), name="section-detail"),
    path("sections/<int:pk>/edit/", locations_views.SectionUpdate.as_view(), name="section-edit"),
    path("sections/<int:pk>/delete/", locations_views.SectionDelete.as_view(), name="section-delete"),
    path("sections/<int:oldpk>/merge/<int:newpk>/", locations_views.SectionMerge.as_view(), name="section-merge"),

    path("departments/", users_views.DepartmentList.as_view(), name="department-list"),
    path("departments/add/", users_views.DepartmentCreate.as_view(), name="department-add"),
    path("departments/<int:pk>/", users_views.DepartmentDetail.as_view(), name="department-detail"),
    path("departments/<int:pk>/edit/", users_views.DepartmentUpdate.as_view(), name="department-edit"),
    path("departments/<int:pk>/adduser/", users_views.DepartmentAddUser.as_view(), name="department-add-user"),

lagerregal/devicetags/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from lagerregal.devices.models import Device


# Create your models here.
class Devicetag(models.Model):
    name = models.CharField(max_length=200, unique=True)
    devices = models.ManyToManyField(Device, related_name="tags")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Device Tag")
        verbose_name_plural = _("Devicegtag")
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("devicetag-edit", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("devicetag-edit", kwargs={"pk": self.pk})

lagerregal/locations/models.py
import reversion
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Section(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Section")
        verbose_name_plural = _("Sections")
        ordering = ["name"]

    def get_absolute_url(self):
        return reverse("section-detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("section-edit", kwargs={"pk": self.pk})


@reversion.register()
class Building(models.Model):
    name = models.CharField(_("Name"), max_length=200, unique=True)
    street = models.CharField(_("Street"), max_length=100, blank=True)
    number = models.CharField(_("Number"), max_length=30, blank=True)
    zipcode = models.CharField(_("ZIP Code"), max_length=5, blank=True)
    city = models.CharField(_("City"), max_length=100, blank=True)
    state = models.CharField(_("State"), max_length=100, blank=True)
    country = models.CharField(_("Country"), max_length=100, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Building")
        verbose_name_plural = _("Buildings")
        ordering = ["name"]
        db_table = "devices_building"

    def get_absolute_url(self):
        return reverse("building-detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("building-edit", kwargs={"pk": self.pk})


@reversion.register()
class Room(models.Model):
    name = models.CharField(_("Name"), max_length=200)
    building = models.ForeignKey(Building, null=True, on_delete=models.SET_NULL)
    section = models.ForeignKey(Section, null=True, on_delete=models.SET_NULL, related_name="rooms", blank=True)

    def __str__(self):
        if self.building:
            return self.name + " (" + str(self.building) + ")"
        else:
            return self.name

    class Meta:
        verbose_name = _("Room")
        verbose_name_plural = _("Rooms")
        ordering = ["name"]
        db_table = "devices_room"

    def get_absolute_url(self):
        return reverse("room-detail", kwargs={"pk": self.pk})

    def get_edit_url(self):
        return reverse("room-edit", kwargs={"pk": self.pk})

lagerregal/devicetags/forms.py
from django import forms

from lagerregal.devicetags.models import Devicetag
from lagerregal.utils import Select2MultipleWidget


class TagForm(forms.ModelForm):
    class Meta:
        model = Devicetag
        exclude = ["devices"]


class DeviceTagForm(forms.Form):
    error_css_class = "has-error"
    tags = forms.ModelMultipleChoiceField(
        Devicetag.objects.all(),
        widget=Select2MultipleWidget(attrs={"data-token-separators": '[",", " "]'}),
    )

lagerregal/devicetypes/forms.py
from django import forms

from lagerregal.devicetypes.models import Type


class TypeForm(forms.ModelForm):
    error_css_class = "has-error"
    extra_fieldcount = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Type
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        if "data" in kwargs:
            extra_fields = kwargs["data"]["extra_fieldcount"]
        else:
            extra_fields = 1

        super().__init__(*args, **kwargs)
        self.fields["extra_fieldcount"].initial = extra_fields

        for index in range(int(extra_fields)):
            # generate extra fields in the number specified via extra_fields
            self.fields[f"extra_field_{index}"] = forms.CharField(
                label="Extra Attribute",
                widget=forms.TextInput(attrs={"class": "extra_attribute form-control"}),
                required=False,
            )

lagerregal/users/forms.py
from django import forms

from lagerregal.users.models import DepartmentUser
from lagerregal.users.models import Lageruser


class AvatarForm(forms.ModelForm):
    error_css_class = "has-error"
    avatar_clear = forms.BooleanField(required=False)

    class Meta:
        model = Lageruser
        fields = ["avatar"]
        widgets = {"avatar": forms.FileInput()}


class DepartmentAddUserForm(forms.ModelForm):
    error_css_class = "has-error"

    class Meta:
        model = DepartmentUser
        widgets = {"department": forms.HiddenInput()}
        fields = "__all__"

lagerregal/main/views.py
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from lagerregal.devices.forms import LendForm
from lagerregal.devices.models import Device
from lagerregal.main.models import DashboardWidget
from lagerregal.main.widgets import WIDGET_NAMES
from lagerregal.main.widgets import WIDGETS
from lagerregal.users.models import Lageruser


class Home(TemplateView):
    template_name = "home.html"

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated and not self.request.user.is_staff:
            return redirect("userprofile")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if not self.request.user.is_staff:
            return context

        context["widgets_left"] = (
            DashboardWidget.objects
            .filter(user=self.request.user, column="l")
            .order_by("index")
        )
        context["widgets_right"] = (
            DashboardWidget.objects
            .filter(user=self.request.user, column="r")
            .order_by("index")
        )
        userwidget_list = dict(WIDGET_NAMES)
        widgetlist = [
            x[0] for x in DashboardWidget.objects.filter(user=self.request.user).values_list("widgetname")
        ]

        for widget in widgetlist:
            context.update(WIDGETS[widget].get_context_data(self.request.user, only_user=True))

        for w in context["widgets_left"]:
            if w.widgetname in userwidget_list:
                del userwidget_list[w.widgetname]
            else:
                w.delete()

        for w in context["widgets_right"]:
            if w.widgetname in userwidget_list:
                del userwidget_list[w.widgetname]
            else:
                w.delete()
        context["widgets_list"] = userwidget_list
        context["lendform"] = LendForm()
        context["lendform"].fields["device"].choices = [
            [device[0], str(device[0]) + " - " + device[1]] for device in (
                Device
                .devices_for_departments(self.request.user.departments.all())
                .filter(trashed=None, currentlending=None, archived=None)
                .values_list("id", "name")
            )
        ]
        context["lendform"].fields["device"].choices.insert(0, ["", "---------"])
        context["userlist"] = Lageruser.objects.filter(is_active=True).values(
            "pk", "username", "first_name", "last_name"
        )
        context["breadcrumbs"] = [("", _("Dashboard"))]

        return context

lagerregal/templates/locations/building_detail.html
{% extends "base.html" %}
{% load devicetags %}
{% load i18n %}
{% block title %}{{ building.name }}{% endblock %}

{% block header %}
    {% trans "Building" %}: {{ building.name }}
{% endblock %}

{% block pullright %}
    {% if perms.devices.change_building %}
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-share"></i> {% trans "Merge" %}
            </button>
            <ul class="dropdown-menu" role="menu">
                {% for merge in merge_list %}
                    <li><a class="dropdown-item" href="{% url 'building-merge' building.pk merge.pk %}">{{ merge.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% editbutton "building-edit" object.id %}
    {% endif %}
    {% if perms.devices.delete_building %}
        {% deletebutton "building-delete" object.id %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-5">
            <table class="table table-bordered table-striped">
                <tbody>
                <tr>
                    <td>{% trans "Street" %}</td>
                    <td>{{ building.street }} {{ building.number }}</td>
                </tr>
                <tr>
                    <td>{% trans "ZIP Code" %}</td>
                    <td>{{ building.zipcode }}</td>
                </tr>
                <tr>
                    <td>{% trans "City" %}</td>
                    <td>{{ building.city }}</td>
                </tr>
                <tr>
                    <td>{% trans "State" %}</td>
                    <td>{{ building.state }}</td>
                </tr>
                <tr>
                    <td>{% trans "Country" %}</td>
                    <td>{{ building.country }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-7">
            {% if device_list %}
                <h4>{% trans "Devices" %}</h4>
                <table id="devicetable" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>{% trans "Name" %}</th>
                            <th>{% trans "Inventory Number" %}</th>
                            <th>{% trans "Device Type" %}</th>
                            <th>{% trans "Room" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for device in device_list %}
                            <tr>
                                <td><a href="{% url 'device-detail' device.id %}">{{ device.name }}</a></td>
                                <td>{{ device.inventorynumber }}</td>
                                <td>{{ device.devicetype__name }}</td>
                                <td>{{ device.room__name }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

lagerregal/templates/locations/building_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Buildings" %}{% endblock %}

{% block header %}
    {% trans "Buildings" %}
{% endblock %}

{% block pullright %}
    {% if perms.devices.add_building %}
        <a href="{% url 'building-add' %}" class="btn btn-primary">
            <i class="fa fa-plus"></i> {% trans "Add Building" %}
        </a>
    {% endif %}
    {% include "snippets/widgets/filter_dropdown.html" with field=viewform.sorting %}
    {% include "snippets/filterform.html" %}
{% endblock %}

{% block content %}
    {% include "snippets/pagination.html" %}
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>{% trans "Name" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for building in building_list %}
                <tr>
                    <td>
                        <a href="{% url 'building-detail' building.id %}">{{ building.name|default:_("(None)") }}</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include "snippets/pagination.html" %}
{% endblock %}

lagerregal/templates/locations/room_detail.html
{% extends "base.html" %}
{% load devicetags %}
{% load i18n %}

{% block title %}{{ room.name }}{% endblock %}

{% block header %}
    {% trans "Room" %}: {{ room.name }}
{% endblock %}

{% block pullright %}
    {% if perms.devices.change_room %}
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-share"></i> {% trans "Merge" %}
            </button>
            <ul class="dropdown-menu" role="menu">
                {% for merge in merge_list %}
                    <li><a class="dropdown-item" href="{% url 'room-merge' room.pk merge.id %}">{{ merge.name }} ({{ merge.building__name }})</a></li>
                {% endfor %}
            </ul>
        </div>
        {% editbutton "room-edit" object.id %}
    {% endif %}
    {% if perms.devices.delete_room %}
        {% deletebutton "room-delete" object.id %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-5">
            <dl class="dl-horizontal">
                <dt>{% trans "Building" %}</dt>
                <dd>
                    {% if room.building %}
                        <a href="{% url 'building-detail' room.building.id %}">{{ room.building }}</a>
                    {% else %}
                        &mdash;
                    {% endif %}
                </dd>
            </dl>
        </div>
        <div class="col-md-7">
            {% if perms.devices.view_device %}
                <h4>{% trans "Device" %}</h4>
                {% if device_list %}
                    <table id="devicetable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>{% trans "Name" %}</th>
                                <th>{% trans "Inventory Number" %}</th>
                                <th>{% trans "Device Type" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for device in device_list %}
                                <tr>
                                    <td><a href="{% url 'device-detail' device.id %}">{{ device.name }}</a></td>
                                    <td>{{ device.inventorynumber }}</td>
                                    <td>{{ device.devicetype__name }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

lagerregal/templates/locations/room_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Rooms" %}{% endblock %}

{% block header %}
    {% trans "Rooms" %}
{% endblock %}

{% block pullright %}
    {% if perms.devices.add_room %}<a href="{% url 'room-add' %}" class="btn btn-primary">
        <i class="fa fa-plus"></i> {% trans "Add Room" %}</a>
    {% endif %}
    {% include "snippets/widgets/filter_dropdown.html" with field=viewform.sorting %}
    {% include "snippets/filterform.html" %}
{% endblock %}

{% block content %}
    {% include "snippets/pagination.html" %}
    <table id="roomtable" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Building" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for room in room_list %}
                <tr>
                    <td><a href="{% url 'room-detail' room.id %}">{{ room.name|default:_("(None)") }}</a></td>
                    <td>{{ room.building }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include "snippets/pagination.html" %}
{% endblock %}

lagerregal/templates/locations/section_detail.html
{% extends "base.html" %}
{% load devicetags %}
{% load i18n %}

{% block title %}{{ section.name }}{% endblock %}

{% block header %}
    {% trans "Room" %}: {{ section.name }}
{% endblock %}

{% block pullright %}
    {% if perms.locations.change_section %}
        <div class="btn-group">
            <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                <i class="fa fa-share"></i> {% trans "Merge" %}
            </button>
            <ul class="dropdown-menu" role="menu">
                {% for merge in merge_list %}
                    <li><a class="dropdown-item" href="{% url 'section-merge' section.pk merge.id %}">{{ merge.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        {% editbutton "section-edit" object.id %}
    {% endif %}
    {% if perms.locations.delete_section %}
        {% deletebutton "section-delete" object.id %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-5">
            <h4>{% trans "Rooms" %}</h4>
            <table id="roomtable" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>{% trans "Name" %}</th>
                        <th>{% trans "Building" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for room in section.rooms.all %}
                        <tr>
                            <td><a href="{% url 'room-detail' room.id %}">{{ room.name }}</a></td>
                            <td>{{ room.building }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-7">
            {% if perms.devices.view_device %}
                <h4>{% trans "Devices" %}</h4>
                {% if device_list %}
                    <table id="devicetable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>{% trans "Name" %}</th>
                                <th>{% trans "Inventory Number" %}</th>
                                <th>{% trans "Device Type" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for device in device_list %}
                                <tr>
                                    <td><a href="{% url 'device-detail' device.id %}">{{ device.name }}</a></td>
                                    <td>{{ device.inventorynumber }}</td>
                                    <td>{{ device.devicetype__name }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

lagerregal/templates/locations/section_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Sections" %}{% endblock %}

{% block header %}
    {% trans "Sections" %}
{% endblock %}

{% block pullright %}
    {% if perms.devicetags.add_devicetag %}
        <a href="{% url 'section-add' %}" class="btn btn-primary">
            <i class="fa fa-plus"></i> {% trans "Add Section" %}
        </a>
    {% endif %}
    {% include "snippets/widgets/filter_dropdown.html" with field=viewform.sorting %}
    {% include "snippets/filterform.html" %}
{% endblock %}

{% block content %}
    {% include "snippets/pagination.html" %}
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>{% trans "Name" %}</th>
            </tr>
        </thead>
        {% for section in section_list %}
            <tr>
                <td><a href="{% url 'section-detail' section.id %}">{{ section.name|default:_("(None)") }}</a></td>
            </tr>
        {% endfor %}
    </table>
    {% include "snippets/pagination.html" %}
{% endblock %}